#if !canImport(ObjectiveC)
import XCTest

extension crackyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__crackyTests = [
        ("testExample", testExample),
        ("testIsUniqueTest", testIsUniqueTest),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(crackyTests.__allTests__crackyTests),
    ]
}
#endif
